AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla para permitir que las instancias EC2 en los AWS Academy Learner Labs se inicien automáticamente al detenerse tras la finalizacion de un Lab
Parameters:
  RolFuncionLambda:
    Type: String
    Description: Introduzca el ARN del LabRole, puedes conseguirlo desde el servicio AWS Identity and Access Management
Resources:
  InicioAutomatico:
    Description: Inicia una instancia EC2 detenida con la etiqueta 'inactividad' con el valor 'no'
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Timeout: 15
      Role: 
        Ref: RolFuncionLambda
      Code:
        ZipFile: |
          import boto3
          import logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          ec2client = boto3.resource('ec2')

          def handler(event, context):
            idInstancia = event['detail']['instance-id']
            instancia = ec2client.Instance(idInstancia)
            if instancia.state['Name'] == "stopped":
              iniciada = False
              for tag in instancia.tags:
                if tag['Key'] == 'inactividad' and tag['Value'] == 'no':
                  instancia.start()
                  mensaje = 'La instancia EC2 con ID '+idInstancia+' estaba parada y se inicia de nuevo'
                  iniciada = True
                  break
              if not iniciada:
                mensaje = 'La instancia EC2 con ID '+idInstancia+' estaba parada y no se iniciará de nuevo'
            else:
              mensaje = 'Evento procesado con anterioridad para la instancia EC2 con ID '+idInstancia
            logger.info(mensaje)
            return {"message":mensaje}
  ReglaInstanciaDetenida:
    Type: AWS::Events::Rule
    Properties:
      Description: Regla que captura los cambios de estado de una instancia EC2
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
        detail:
          state:
            - stopped
      Name: EventBridge-regla-iniciar-instancia
      State: "ENABLED"
      Targets:
        - 
          Arn:
            Fn::GetAtt:
              - "InicioAutomatico"
              - "Arn"
          Id: "DestinoFuncion1"
  PermisoEventBridgeInvocacionLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref "InicioAutomatico"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ReglaInstanciaDetenida"
          - "Arn"