AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla para permitir que las instancias EC2 en los AWS Academy Learner Labs se inicien automáticamente al detenerse tras la finalizacion de un Lab
Resources:
  InicioAutomatico:
    Description: Inicia una instancia EC2 detenida con la etiqueta 'inactividad' con el valor 'no'
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Timeout: 15
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
      Code:
        ZipFile: inicia_instancia.zip
  ReglaInstanciaDetenida:
    Type: AWS::Events::Rule
    Properties:
      Description: Regla que captura los cambios de estado de una instancia EC2
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
        detail:
          state:
            - stopped
      Name: EventBridge-regla-iniciar-instancia
      State: "ENABLED"
      Targets:
        - 
          Arn:
            Fn::GetAtt:
              - "InicioAutomatico"
              - "Arn"
          Id: "DestinoFuncion1"
  PermisoEventBridgeInvocacionLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref "InicioAutomatico"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ReglaInstanciaDetenida"
          - "Arn"